<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="48376" started-at="2017-01-24T13:55:53Z" finished-at="2017-01-24T13:56:41Z">
    <groups>
    </groups>
    <test name="RegressionTest" duration-ms="48376" started-at="2017-01-24T13:55:53Z" finished-at="2017-01-24T13:56:41Z">
      <class name="testscripts.VerifyHomePage">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testscripts.VerifyHomePage@ae45eb6]" name="setUp" is-config="true" duration-ms="14625" started-at="2017-01-24T19:25:53Z" finished-at="2017-01-24T19:26:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyPage()[pri:0, instance:testscripts.VerifyHomePage@ae45eb6]" name="verifyPage" duration-ms="38" started-at="2017-01-24T19:26:07Z" finished-at="2017-01-24T19:26:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPage -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testscripts.VerifyHomePage@ae45eb6]" name="tearDown" is-config="true" duration-ms="1074" started-at="2017-01-24T19:26:40Z" finished-at="2017-01-24T19:26:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testscripts.VerifyHomePage -->
      <class name="testscripts.VerifyLoginPageWithReports1">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testscripts.VerifyLoginPageWithReports1@7cd62f43]" name="setUp" is-config="true" duration-ms="13172" started-at="2017-01-24T19:26:08Z" finished-at="2017-01-24T19:26:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyLogin()[pri:0, instance:testscripts.VerifyLoginPageWithReports1@7cd62f43]" name="verifyLogin" duration-ms="17749" started-at="2017-01-24T19:26:21Z" finished-at="2017-01-24T19:26:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[sign out link is not present expected [Sign Out] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: sign out link is not present expected [Sign Out] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at pages.LoginPage.verifySignOutLink(LoginPage.java:34)
	at testscripts.VerifyLoginPageWithReports1.verifyLogin(VerifyLoginPageWithReports1.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:testscripts.VerifyLoginPageWithReports1@7cd62f43]" name="tearDown" is-config="true" duration-ms="1695" started-at="2017-01-24T19:26:38Z" finished-at="2017-01-24T19:26:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLogin status=FAILURE method=VerifyLoginPageWithReports1.verifyLogin()[pri:0, instance:testscripts.VerifyLoginPageWithReports1@7cd62f43] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testscripts.VerifyLoginPageWithReports1 -->
    </test> <!-- RegressionTest -->
  </suite> <!-- Suite -->
</testng-results>
